/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fff9ec',
        'surface-dim': '#e3dabc',
        'surface-bright': '#fff9ec',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fdf3d4',
        'surface-container': '#f7eecf',
        'surface-container-high': '#f1e8c9',
        'surface-container-highest': '#ebe2c4',
        'surface-variant': '#ebe2c4',
        'on-surface': '#1f1c09',
        'on-surface-variant': '#434937',
        outline: '#737a65',
        'outline-variant': '#c3c9b2',
        primary: '#466800',
        'on-primary': '#ffffff',
        'primary-container': '#b1ea55',
        'on-primary-container': '#456800',
        'primary-fixed': '#bbf45e',
        secondary: '#765b00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fec715',
        'on-secondary-container': '#6e5400',
        tertiary: '#5b6056',
        'tertiary-container': '#d5dacd',
        'on-tertiary-container': '#5a6056',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'brand-ink': '#0C0900',
        'brand-sage': '#B8BDB1',
        canvas: '#F5F5F3',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        xxl: '64px',
        'container-max': '1440px',
      },
      fontFamily: {
        outfit: ['Outfit', 'system-ui', 'sans-serif'],
        inter: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        h1: ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        h3: ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      boxShadow: {
        soft: '0px 10px 30px rgba(12, 9, 0, 0.05)',
        canvas: '0px 20px 50px rgba(0, 0, 0, 0.1)',
      },
      maxWidth: {
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
};
