/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        /* Studio chrome — cool tool palette; patient preview keeps its own tokens */
        surface: '#FAFAF9',
        'surface-dim': '#E8E8E6',
        'surface-bright': '#FFFFFF',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F4F4F2',
        'surface-container': '#EEEEEC',
        'surface-container-high': '#E6E6E3',
        'surface-container-highest': '#DEDEDB',
        'surface-variant': '#E6E6E3',
        'on-surface': '#141816',
        'on-surface-variant': '#4A524E',
        outline: '#6B7370',
        'outline-variant': '#D4D6D3',
        primary: '#1A5C52',
        'on-primary': '#FFFFFF',
        'primary-container': '#D4EBE6',
        'on-primary-container': '#0F3D36',
        'primary-fixed': '#B8DED6',
        secondary: '#3D4643',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#E4E8E5',
        'on-secondary-container': '#2A322F',
        tertiary: '#5B6056',
        'tertiary-container': '#E4E8E5',
        'on-tertiary-container': '#3A403C',
        error: '#B42318',
        'error-container': '#FEE4E2',
        'on-error-container': '#7A271A',
        'brand-ink': '#0F1C1A',
        'brand-sage': '#C5CBC8',
        canvas: '#F0F0EE',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        xxl: '64px',
        'container-max': '1440px',
      },
      fontFamily: {
        outfit: ['Outfit', 'system-ui', 'sans-serif'],
        inter: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        h1: ['40px', { lineHeight: '1.15', letterSpacing: '-0.03em', fontWeight: '650' }],
        h2: ['28px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        h3: ['20px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.55', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '1.45', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '1.2', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.01em', fontWeight: '550' }],
      },
      boxShadow: {
        soft: '0 1px 2px rgba(15, 28, 26, 0.04), 0 8px 24px rgba(15, 28, 26, 0.04)',
        canvas: '0 12px 40px rgba(15, 28, 26, 0.08)',
      },
      maxWidth: {
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
};
